### ISSUE TITLE
Create Collection Wizard 에서 Test Field Mapping 시 에러

### ISSUE THREAD

**Issue by tenb2000** [fastcat-co/fastcatsearch#38]
관리도구 Manager - Create Collection Wizard 에서 Test Field Mapping 클릭시 아래와 같은 에러가 납니다.
JDBC 연결 잘 되고, Query Test 시에는 Data를 잘 가져 옵니다.
그러나 Set Field Schema 단계에서 Test Field Mapping 버튼을 클릭하면 Data 를 가져 오지 못하고, 아래와 같은 에러를 분출 합니다.

Search 엔진 쪽 로그와 Console 쪽 로그를 모루 첨부 하오니, 해결 방안에 대해서 답변 부탁 드립니다.
설정변경은 전혀 없었고, fastcatsearch, fastcatsearch-console 두개의 package를 maven 빌드 후 실행 했습니다. 이것 이외에는 특별한 문제점 없이 잘 진행 되었습니다. 

Search 엔진 에러:
[2015-06-01 15:07:58,247 ERROR] (ServiceAction.java:29) ServiceAction Error!
java.lang.NoSuchMethodException: org.fastcatsearch.datasource.reader.DBReader.<init>(java.io.File, org.fastcatsearch.ir.config.SingleSourceConfig, org.fastcatsearch.datasource.SourceModifier, java.lang.String)
    at java.lang.Class.getConstructor0(Class.java:2892) ~[na:1.7.0_79]
    at java.lang.Class.getConstructor(Class.java:1723) ~[na:1.7.0_79]
    at org.fastcatsearch.http.action.management.collections.TestSourceReaderAction.doAuthAction(TestSourceReaderAction.java:55) ~[fastcatsearch-server-2.21.3-SNAPSHOT.jar:na]
    at org.fastcatsearch.http.action.AuthAction.doAction(AuthAction.java:59) ~[fastcatsearch-server-2.21.3-SNAPSHOT.jar:na]
    at org.fastcatsearch.http.action.ServiceAction.runAction(ServiceAction.java:27) ~[fastcatsearch-server-2.21.3-SNAPSHOT.jar:na]
    at org.fastcatsearch.http.action.HttpAction.run(HttpAction.java:52) [fastcatsearch-server-2.21.3-SNAPSHOT.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
[2015-06-01 15:07:58,249 ERROR] (HttpAction.java:55) Action수행중 에러발생.
org.fastcatsearch.util.ResultWriterException: Stream closed
    at org.fastcatsearch.util.JSONResponseWriter.object(JSONResponseWriter.java:37) ~[fastcatsearch-server-2.21.3-SNAPSHOT.jar:na]
    at org.fastcatsearch.http.action.ServiceAction.runAction(ServiceAction.java:34) ~[fastcatsearch-server-2.21.3-SNAPSHOT.jar:na]
    at org.fastcatsearch.http.action.HttpAction.run(HttpAction.java:52) ~[fastcatsearch-server-2.21.3-SNAPSHOT.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: org.json.JSONException: Stream closed
    at org.json.JSONWriter.append(JSONWriter.java:121) ~[org.json-20130213.jar:na]
    at org.json.JSONWriter.object(JSONWriter.java:239) ~[org.json-20130213.jar:na]
    at org.fastcatsearch.util.JSONResponseWriter.object(JSONResponseWriter.java:34) ~[fastcatsearch-server-2.21.3-SNAPSHOT.jar:na]
    ... 5 common frames omitted
Caused by: java.io.IOException: Stream closed
    at java.io.BufferedWriter.ensureOpen(BufferedWriter.java:116) ~[na:1.7.0_79]
    at java.io.BufferedWriter.write(BufferedWriter.java:221) ~[na:1.7.0_79]
    at java.io.Writer.write(Writer.java:157) ~[na:1.7.0_79]
    at org.json.JSONWriter.append(JSONWriter.java:119) ~[org.json-20130213.jar:na]
    ... 7 common frames omitted

관리도구 Console 에러 :
15:07:58.266 [qtp21377352-25] ERROR o.f.c.w.c.AbstractController - 
org.apache.http.client.ClientProtocolException: null
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:188) ~[httpclient-4.3.jar:4.3]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.3.jar:4.3]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214) ~[httpclient-4.3.jar:4.3]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160) ~[httpclient-4.3.jar:4.3]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:136) ~[httpclient-4.3.jar:4.3]
    at org.fastcatsearch.console.web.http.ResponseHttpClient$AbstractMethod.requestJSON(ResponseHttpClient.java:126) ~[classes/:na]
    at org.fastcatsearch.console.web.controller.MainController.request(MainController.java:329) ~[classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
    at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:219) [spring-web-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132) [spring-web-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) [spring-webmvc-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745) [spring-webmvc-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:686) [spring-webmvc-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80) [spring-webmvc-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925) [spring-webmvc-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856) [spring-webmvc-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:936) [spring-webmvc-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:838) [spring-webmvc-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) [servlet-api-3.0.jar:na]
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:812) [spring-webmvc-3.2.4.RELEASE.jar:3.2.4.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [servlet-api-3.0.jar:na]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [jetty-servlet-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501) [jetty-servlet-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533) [jetty-security-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [jetty-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428) [jetty-servlet-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [jetty-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255) [jetty-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) [jetty-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.Server.handle(Server.java:370) [jetty-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) [jetty-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982) [jetty-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043) [jetty-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jetty-http-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667) [jetty-io-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) [jetty-io-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.14.v20131031.jar:8.1.14.v20131031]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: org.apache.http.HttpException: Unsupported Content-Coding: UTF-8
    at org.apache.http.client.protocol.ResponseContentEncoding.process(ResponseContentEncoding.java:98) ~[httpclient-4.3.jar:4.3]
    at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:139) ~[httpcore-4.3.jar:4.3]
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:199) ~[httpclient-4.3.jar:4.3]
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85) ~[httpclient-4.3.jar:4.3]
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108) ~[httpclient-4.3.jar:4.3]
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186) ~[httpclient-4.3.jar:4.3]
    ... 48 common frames omitted

**Comment by songaal** [comment]
버그 해결됨. 
https://github.com/fastcat-co/fastcatsearch/releases/tag/v2.21.3
